version: '3.8'
services:
  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    networks:
      - task-network
    depends_on:
      - backend

  backend:
    image: python:3.12-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "pip install -r requirements.txt && flask run --host=0.0.0.0"
    ports:
      - "5000:5000"
    networks:
      - task-network
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://taskuser:taskpassword@database:5432/taskdb
    depends_on:
      - database

  database:
    image: postgres:15-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=taskuser
      - POSTGRES_PASSWORD=taskpassword
      - POSTGRES_DB=taskdb
    networks:
      - task-network

volumes:
  db_data:

networks:
  task-network:
    driver: bridge